userLayers,Слои пользователя
depthCntProp,Свойста контура глубины
userIconImport,Импорт значка пользователя
selectIcon,Выбор значка
linePlotting,Рисование линии
userObjLoad,Загрузка объекта пользователя
depthAreas,Допустимые осадки
docums,Документы
officialInfo,Официальная информация
moreInfo,Уточняющая информация
otherInfo,Прочая информация
userIcnLib,Библиотека значков пользователя
layerEditor,Редактор слоя
userLayers,Слои пользователя
areaName,Название района
maxDrg,Мкс.осдк
category,Категория
info,Информация
add,Доб
delete,Удал
rename,Переим
name,Название
icon,Значок
iconDelConf,Вы хотите удалить выбранный значок из бибиотеки
iconRename,Переименование значка
nameEnter,Введите новое название
iconGrp,Группа значков
polyline,Полилиния
polygon,Полигон
depthArea,Контур глубины
cancel,Отм
save,Сохр
new,Созд
edit,Измен
changesLoose,Не сохранять изменения
visible,Виден
ok,OK
plsSpecName,Укажите имя
plsSpecUrlOrUpl,Укажите URL или загрузите файл
polylineEdit,Создание/правка полилинии
polygonEdit,Создание/правка полигона
icnGroupEdit,Создание/правка группы значков
userObj,Объект пользователя
objName,Название объекта
objNameShort,Назв.объекта
type,Тип
objNameEnter,Введите название объекта
newPolyline,Новая полилиния
newPolygon,Новый полигон
newIcon,Новый значок
newIconGrp,Новая группа значков
newBerth,Новый причал
newDepthCnt,Новый контур глубины
objList,Список объектов
loadUserObj,Загр польз.объекта
loadEditUserObj,Загр/ред польз.объекта
backToPrevMenu,К предыд.меню
getWeatherPredHere,Прогноз погоды в точке
objEditor,Объектный редактор
atThisPoint,В этой точке...
berth,Причал
saveObject,Сохранить объект
doNothing,Ничего не делать
settings,Настройки
baseMap,Базовая карта
overlays,Слои наложения
lat,Шир
lon,Долг
range,Дист
correction,Уточнение
id,ID
maxDraught,Макс.осадка, м
fillColor,Цвет заливки
color,Цвет
opacity,Прозрачность
polygonProps,Свойства полигона
polylineProps,Свойства полилинии
style,Стиль
lineWidth,Толщина линии
dash,Пунктир
dot,Точки
solid,Сплошная
userInfoList,Список уточнений
userInfoEdit,Редактирование уточнения
param,Параметр
value,Значение
infoItemEdit,Изменение уточняющей информации
newValue,Новое значение
import,Импорт
pressToSetup,Нажмите для изменения настроек
deleteUserInfo,Удалить выделенную уточняющую информацию?
deleteAttachment,Удалить выделенное приложение?
close,Закр
applyUpdates,Применить обновления
attachments,Приложения
attachment,Приложение
objAtts,Приложения к объекту
upload,Загрузка
view,Просм
updateHistory,История обновлений
date,Дата
action,Действие
actionShort,Дйств
oldValue,Старое значение
userInfoChanged,Уточнение изменено
newAttachment,Новое приложение
delAttachment,Приложение удалено
delObject,Объект удален
newObject,Новый объект
delLayer,Слой удален
newLayer,Новый слой
draftChanged,Осадка изменена
showTimeline,Показать временную шкалу
cancel2,Отмена
timeline,Временная шкала
show,Показать
position,Координаты
navStatus,Нав.статус
aisTargets,Цели AIS
aisTargetsMT,Цели AIS (MarineTraffic)
properties,Свойства
shape,Форма
vessels,Суда
lastReport,Последний отчет
trackShort,Тр
trackSettings,Параметры трека
from,От
to,До
mode,Режим
show,Показать
trackShowSimple,Только трек
trackShowFull,Трек и точки отчетов
sensorData,Данные сенсоров
noData,Нет данных
noTrackData,Нет данных по треку
error,Ошибка
dateTime,Дата/время
sensor,Сенсор
timeSettings,Настройки времени
dataInterval,Интервал (сек)
graph,График
time,Время
